/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package barangay.information.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ASUS ROG STRIX
 */
public class FamilyMembers extends javax.swing.JInternalFrame {

    /**
     * Creates new form FamilyMembers
     */
    public FamilyMembers() {
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        initComponents();
  Familyheads();
       
    }
Connection Con = null;
Statement St = null;
ResultSet Rs= null;
public void FamilyMembers(){
    try{
        Con= DriverManager.getConnection("jdbc:mysql://localhost:3307/brgydata","root","");
        St = Con.createStatement();
        
        Rs = St.executeQuery("SELECT * FROM familyhead JOIN familyhome ON familyhead.Head_ID = familyhome.headID_fk JOIN familymembers ON familyhome.Home_ID = familymembers.homeID_fk WHERE familyhead.Family_Heads = '"+Familyhead_cb.getSelectedItem()+"'");
        Familymembersinfo.setModel(DbUtils.resultSetToTableModel(Rs));
        Familymembersinfo.repaint();
        Rs.close();
        St.close();
        Con.close();
    }catch(SQLException e){
        e.printStackTrace();
    }
}
public void Familyheads() {
    Set<String> items = new HashSet<>();
    try {
        Con= DriverManager.getConnection("jdbc:mysql://localhost:3307/brgydata","root","");
        St = Con.createStatement();
        Rs = St.executeQuery("SELECT Family_Heads FROM familyhead");

        // Add the family head names to the combo box
        while (Rs.next()) {
            String name = Rs.getString("Family_Heads");
            if (!items.contains(name)) { // Check if item already exists in the Set
                items.add(name);
            }
        }
        for (String name : items) {
            Familyhead_cb.addItem(name); // Add items to the JComboBox
        }
        // Close the result set, statement, and connection objects
        Rs.close();
        St.close();
        Con.close();
    } catch (Exception ex) {
        Logger.getLogger(memberaddinfo.class.getName()).log(Level.SEVERE, null, ex);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Familymembersinfo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Familyhead_cb = new javax.swing.JComboBox<>();
        panel2 = new java.awt.Panel();
        jLabel16 = new javax.swing.JLabel();

        panel1.setBackground(new java.awt.Color(0, 153, 51));

        Familymembersinfo.setAutoCreateRowSorter(true);
        Familymembersinfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14", "Title 15", "Title 16", "Title 17"
            }
        ));
        Familymembersinfo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(Familymembersinfo);
        if (Familymembersinfo.getColumnModel().getColumnCount() > 0) {
            Familymembersinfo.getColumnModel().getColumn(0).setResizable(false);
            Familymembersinfo.getColumnModel().getColumn(0).setPreferredWidth(150);
            Familymembersinfo.getColumnModel().getColumn(1).setResizable(false);
            Familymembersinfo.getColumnModel().getColumn(1).setPreferredWidth(150);
            Familymembersinfo.getColumnModel().getColumn(2).setResizable(false);
            Familymembersinfo.getColumnModel().getColumn(2).setPreferredWidth(150);
            Familymembersinfo.getColumnModel().getColumn(3).setResizable(false);
            Familymembersinfo.getColumnModel().getColumn(3).setPreferredWidth(150);
            Familymembersinfo.getColumnModel().getColumn(4).setResizable(false);
            Familymembersinfo.getColumnModel().getColumn(4).setPreferredWidth(150);
            Familymembersinfo.getColumnModel().getColumn(5).setResizable(false);
            Familymembersinfo.getColumnModel().getColumn(5).setPreferredWidth(150);
            Familymembersinfo.getColumnModel().getColumn(6).setResizable(false);
            Familymembersinfo.getColumnModel().getColumn(6).setPreferredWidth(150);
            Familymembersinfo.getColumnModel().getColumn(7).setResizable(false);
            Familymembersinfo.getColumnModel().getColumn(7).setPreferredWidth(150);
            Familymembersinfo.getColumnModel().getColumn(8).setResizable(false);
            Familymembersinfo.getColumnModel().getColumn(8).setPreferredWidth(150);
            Familymembersinfo.getColumnModel().getColumn(9).setResizable(false);
            Familymembersinfo.getColumnModel().getColumn(9).setPreferredWidth(150);
            Familymembersinfo.getColumnModel().getColumn(10).setResizable(false);
            Familymembersinfo.getColumnModel().getColumn(10).setPreferredWidth(150);
            Familymembersinfo.getColumnModel().getColumn(11).setResizable(false);
            Familymembersinfo.getColumnModel().getColumn(11).setPreferredWidth(150);
            Familymembersinfo.getColumnModel().getColumn(12).setResizable(false);
            Familymembersinfo.getColumnModel().getColumn(12).setPreferredWidth(150);
            Familymembersinfo.getColumnModel().getColumn(13).setResizable(false);
            Familymembersinfo.getColumnModel().getColumn(13).setPreferredWidth(150);
            Familymembersinfo.getColumnModel().getColumn(14).setResizable(false);
            Familymembersinfo.getColumnModel().getColumn(14).setPreferredWidth(150);
            Familymembersinfo.getColumnModel().getColumn(15).setResizable(false);
            Familymembersinfo.getColumnModel().getColumn(15).setPreferredWidth(150);
            Familymembersinfo.getColumnModel().getColumn(16).setResizable(false);
            Familymembersinfo.getColumnModel().getColumn(16).setPreferredWidth(150);
        }

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel1.setText("Family Head");

        Familyhead_cb.setOpaque(false);
        Familyhead_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Familyhead_cbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Familyhead_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(395, 395, 395))
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Familyhead_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(488, Short.MAX_VALUE))
        );

        panel2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS ROG STRIX\\Downloads\\icons8-family--man-woman-boy-boy-100.png")); // NOI18N
        jLabel16.setText("FAMILY MEMBER INFORMATIONS");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Familyhead_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Familyhead_cbActionPerformed
        
       FamilyMembers();
     
    
    }//GEN-LAST:event_Familyhead_cbActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Familyhead_cb;
    private javax.swing.JTable Familymembersinfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    // End of variables declaration//GEN-END:variables
}
