/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package barangay.information.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ASUS ROG STRIX
 */
public class FamilyHeads extends javax.swing.JInternalFrame {

    /**
     * Creates new form FamilyHeads
     */
    public FamilyHeads() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
      
        
        FamilyHead();
    }
        Connection Con = null;
Statement St = null;
ResultSet Rs= null;
public void FamilyHead(){
    try{
        String fhead = "Head";
        Con= DriverManager.getConnection("jdbc:mysql://localhost:3307/brgydata","root","");
        St = Con.createStatement();
Rs = St.executeQuery("SELECT m.Member_ID,f.Family_Heads,h.House_number, h.Family_Address, m.LastName, m.FirstName, "
        + "m.MiddleName, m.Suffix, m.Age, m.Sex, m.BirthDate, m.Status, m.Relationship, m.Religion, m.PhoneNumber, "
        + "m.Email, m.Educational FROM familyhead f JOIN familyhome h ON f.Head_ID = h.headID_fk JOIN familymembers m "
        + "ON h.Home_ID = m.homeID_fk AND m.Relationship = 'Head'; ");
        Familyheadinfo.setModel(DbUtils.resultSetToTableModel(Rs));
        
    }catch(SQLException e){
        e.printStackTrace();
        
    }}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        panel2 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Familyheadinfo = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panel3 = new java.awt.Panel();
        jPanel4 = new javax.swing.JPanel();
        MemberID = new javax.swing.JTextField();
        FirstName = new javax.swing.JTextField();
        MiddleName = new javax.swing.JTextField();
        LastName = new javax.swing.JTextField();
        Suffix = new javax.swing.JComboBox<>();
        Age = new javax.swing.JTextField();
        Sex = new javax.swing.JComboBox<>();
        Birthday = new javax.swing.JTextField();
        Status = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Address = new javax.swing.JTextField();
        Housenumber = new javax.swing.JTextField();
        Educational = new javax.swing.JComboBox<>();
        PhoneNumber = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Relationship = new javax.swing.JTextField();
        Religion = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Ad = new javax.swing.JLabel();
        House = new javax.swing.JLabel();
        Educatinal1 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        surnamesearch = new javax.swing.JTextField();

        panel1.setBackground(new java.awt.Color(0, 153, 51));

        panel2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS ROG STRIX\\Downloads\\icons8-family-100 (1).png")); // NOI18N
        jLabel1.setText("FAMILY HEADS");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(24, 24, 24))
        );

        Familyheadinfo.setAutoCreateRowSorter(true);
        Familyheadinfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Familyheadinfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Familyheadinfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Member ID", "Family Heads", "First Name", "Middle Name", "Last Name", "Suffix", "Age", "Sex", "Birthday", "Civil Status", "Address", "House Number", "Educational", "Phone Number", "Email", "Relationship", "Religion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Familyheadinfo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        Familyheadinfo.setFillsViewportHeight(true);
        Familyheadinfo.setSelectionBackground(new java.awt.Color(0, 153, 51));
        Familyheadinfo.setShowGrid(false);
        Familyheadinfo.getTableHeader().setReorderingAllowed(false);
        Familyheadinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FamilyheadinfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Familyheadinfo);
        if (Familyheadinfo.getColumnModel().getColumnCount() > 0) {
            Familyheadinfo.getColumnModel().getColumn(0).setResizable(false);
            Familyheadinfo.getColumnModel().getColumn(0).setPreferredWidth(100);
            Familyheadinfo.getColumnModel().getColumn(1).setResizable(false);
            Familyheadinfo.getColumnModel().getColumn(1).setPreferredWidth(150);
            Familyheadinfo.getColumnModel().getColumn(2).setResizable(false);
            Familyheadinfo.getColumnModel().getColumn(2).setPreferredWidth(150);
            Familyheadinfo.getColumnModel().getColumn(3).setResizable(false);
            Familyheadinfo.getColumnModel().getColumn(3).setPreferredWidth(150);
            Familyheadinfo.getColumnModel().getColumn(4).setResizable(false);
            Familyheadinfo.getColumnModel().getColumn(4).setPreferredWidth(150);
            Familyheadinfo.getColumnModel().getColumn(5).setResizable(false);
            Familyheadinfo.getColumnModel().getColumn(5).setPreferredWidth(100);
            Familyheadinfo.getColumnModel().getColumn(6).setResizable(false);
            Familyheadinfo.getColumnModel().getColumn(6).setPreferredWidth(100);
            Familyheadinfo.getColumnModel().getColumn(7).setResizable(false);
            Familyheadinfo.getColumnModel().getColumn(7).setPreferredWidth(100);
            Familyheadinfo.getColumnModel().getColumn(8).setResizable(false);
            Familyheadinfo.getColumnModel().getColumn(8).setPreferredWidth(100);
            Familyheadinfo.getColumnModel().getColumn(9).setResizable(false);
            Familyheadinfo.getColumnModel().getColumn(9).setPreferredWidth(100);
            Familyheadinfo.getColumnModel().getColumn(10).setResizable(false);
            Familyheadinfo.getColumnModel().getColumn(10).setPreferredWidth(200);
            Familyheadinfo.getColumnModel().getColumn(11).setResizable(false);
            Familyheadinfo.getColumnModel().getColumn(11).setPreferredWidth(100);
            Familyheadinfo.getColumnModel().getColumn(12).setResizable(false);
            Familyheadinfo.getColumnModel().getColumn(12).setPreferredWidth(100);
            Familyheadinfo.getColumnModel().getColumn(13).setResizable(false);
            Familyheadinfo.getColumnModel().getColumn(13).setPreferredWidth(100);
            Familyheadinfo.getColumnModel().getColumn(14).setResizable(false);
            Familyheadinfo.getColumnModel().getColumn(14).setPreferredWidth(100);
            Familyheadinfo.getColumnModel().getColumn(15).setResizable(false);
            Familyheadinfo.getColumnModel().getColumn(15).setPreferredWidth(100);
            Familyheadinfo.getColumnModel().getColumn(16).setResizable(false);
            Familyheadinfo.getColumnModel().getColumn(16).setPreferredWidth(100);
        }

        jLabel6.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS ROG STRIX\\Downloads\\icons8-add-administrator-30.png")); // NOI18N
        jLabel6.setText("ADD");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS ROG STRIX\\Downloads\\icons8-update-user-skin-type-7-30.png")); // NOI18N
        jLabel7.setText("UPDATE");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS ROG STRIX\\Downloads\\icons8-remove-user-female-30.png")); // NOI18N
        jLabel8.setText("DELETE");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS ROG STRIX\\Downloads\\icons8-erase-30.png")); // NOI18N
        jLabel9.setText("CLEAR");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        panel3.setLayout(new java.awt.GridLayout(1, 2));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridLayout(0, 1, 0, 6));

        MemberID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(MemberID);

        FirstName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(FirstName);

        MiddleName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(MiddleName);

        LastName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(LastName);

        Suffix.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Jr.", "Sr.", " I", " II", "III", "IV" }));
        Suffix.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(Suffix);

        Age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(Age);

        Sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        Sex.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(Sex);

        Birthday.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(Birthday);

        Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single ", "Married", "Divorced ", "Widowed ", "Separated " }));
        Status.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(Status);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(0, 1, 0, 6));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("MEMBER ID");
        jPanel1.add(jLabel14);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("First Name");
        jPanel1.add(jLabel10);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Middle Name");
        jPanel1.add(jLabel11);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Last Name");
        jPanel1.add(jLabel12);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Suffix");
        jPanel1.add(jLabel15);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Age");
        jPanel1.add(jLabel16);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Sex");
        jPanel1.add(jLabel17);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Birthdate");
        jPanel1.add(jLabel18);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Civil Status");
        jPanel1.add(jLabel19);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(0, 1, 0, 6));

        Address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressActionPerformed(evt);
            }
        });
        jPanel3.add(Address);

        Housenumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(Housenumber);

        Educational.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "College Graduate", "College Undergraduate", "High School Graduate", "High School Undergraduate", "Elementary Graduate", "Elementary Graduate", "Elementary Undergraduate", "None" }));
        jPanel3.add(Educational);

        PhoneNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(PhoneNumber);

        Email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(Email);

        Relationship.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(Relationship);

        Religion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(Religion);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(0, 1, 0, 6));

        Ad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Ad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Ad.setText("Address");
        jPanel2.add(Ad);

        House.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        House.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        House.setText("House Number");
        jPanel2.add(House);

        Educatinal1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Educatinal1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Educatinal1.setText("Educational");
        jPanel2.add(Educatinal1);

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel37.setText("Phone Number +639");
        jPanel2.add(jLabel37);

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel38.setText("Email");
        jPanel2.add(jLabel38);

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel39.setText("Relationship");
        jPanel2.add(jLabel39);

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel40.setText("Religion");
        jPanel2.add(jLabel40);

        jLabel20.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel20.setText("Last Name");

        surnamesearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                surnamesearchMouseClicked(evt);
            }
        });
        surnamesearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                surnamesearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                surnamesearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                surnamesearchKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addGap(31, 31, 31)
                        .addComponent(surnamesearch, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163))))
            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                    .addContainerGap(523, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(327, Short.MAX_VALUE)))
            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                    .addContainerGap(442, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(427, Short.MAX_VALUE)))
            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                    .addContainerGap(772, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(89, Short.MAX_VALUE)))
            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                    .addContainerGap(643, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(176, Short.MAX_VALUE)))
        );

        panel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel1, jPanel4});

        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(surnamesearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(320, 320, 320)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(418, Short.MAX_VALUE))
            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                    .addContainerGap(220, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(517, Short.MAX_VALUE)))
            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                    .addContainerGap(220, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(517, Short.MAX_VALUE)))
            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                    .addContainerGap(227, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(523, Short.MAX_VALUE)))
            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                    .addContainerGap(220, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(518, Short.MAX_VALUE)))
        );

        panel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel1, jPanel4});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FamilyheadinfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FamilyheadinfoMouseClicked
       DefaultTableModel model = (DefaultTableModel)Familyheadinfo.getModel();
        int Myindex = Familyheadinfo.getSelectedRow();
        
        
        
        //member_no.setText(model.getValueAt(Myindex, 2).toString());
        MemberID.setText(model.getValueAt(Myindex, 0).toString());
        FirstName.setText(model.getValueAt(Myindex, 5).toString());
        MiddleName.setText(model.getValueAt(Myindex,6).toString());
        LastName.setText(model.getValueAt(Myindex, 4).toString());
        Suffix.setSelectedItem(model.getValueAt(Myindex, 7).toString());
        Age.setText(model.getValueAt(Myindex, 8).toString());
        Sex.setSelectedItem(model.getValueAt(Myindex, 9).toString());
        Birthday.setText(model.getValueAt(Myindex, 10).toString());
        Status.setSelectedItem(model.getValueAt(Myindex, 11).toString());
        Relationship.setText(model.getValueAt(Myindex, 12).toString());
        Religion.setText(model.getValueAt(Myindex, 13).toString());
        PhoneNumber.setText(model.getValueAt(Myindex, 14).toString());
        Email.setText(model.getValueAt(Myindex, 15).toString());
         Educational.setSelectedItem(model.getValueAt(Myindex,16).toString());
         Address.setText(model.getValueAt(Myindex, 3).toString());
         Housenumber.setText(model.getValueAt(Myindex,2).toString());
        
        
        
        
    }//GEN-LAST:event_FamilyheadinfoMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
       //int numMembers = Integer.parseInt(JOptionPane.showInputDialog("Enter the number of members:"));
    
        int result = JOptionPane.showConfirmDialog(null, 
                "Do you have members?", "Select an Option...",JOptionPane.YES_NO_OPTION);
       
                     if(result == JOptionPane.NO_OPTION){
                        try{
                     Con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/brgydata","root","");
                     
                     
                     PreparedStatement add =Con.prepareStatement("INSERT INTO familyhead(Head_ID,Family_Heads) Values(?,?)");
                     add.setString(1, MemberID.getText());
                     add.setString(2, LastName.getText()+" "+FirstName.getText());
                     
                     
                     
                     PreparedStatement add2 =Con.prepareStatement("INSERT INTO familyhome(Family_Name,Family_Address,House_number,headID_fk,Home_ID) Values(?,?,?,?,?)");
                     add2.setString(1, LastName.getText());
                     add2.setString(2, Address.getText());
                     add2.setString(3, Housenumber.getText());
                     add2.setString(4, MemberID.getText());
                     add2.setString(5, Housenumber.getText());

                     PreparedStatement add3 =Con.prepareStatement("INSERT INTO familymembers(LastName,FirstName,MiddleName,Suffix,Age,Sex,BirthDate,"
                             + "Status,Relationship,Religion,PhoneNumber,Email,Educational,homeID_fk,Member_ID) Values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                     add3.setString(1, LastName.getText());
                     add3.setString(2, FirstName.getText());
                     add3.setString(3, MiddleName.getText());
                     add3.setString(4, Suffix.getSelectedItem().toString());
                     add3.setString(5, Age.getText());
                     add3.setString(6, Sex.getSelectedItem().toString());
                     add3.setString(7, Birthday.getText());
                     add3.setString(8, Status.getSelectedItem().toString());
                     add3.setString(9, Relationship.getText());
                     add3.setString(10, Religion.getText());
                     add3.setString(11, PhoneNumber.getText());
                     add3.setString(12, Email.getText());
                     add3.setString(13, Educational.getSelectedItem().toString());
                     add3.setString(14, Housenumber.getText());
                     add3.setString(15, MemberID.getText());
                     
                    add.executeUpdate();
                     add2.executeUpdate();
                     add3.executeUpdate();


                     JOptionPane.showMessageDialog(this, "Family Head Successfully Added");

                     MemberID.setText("");
                     LastName.setText("");
                     Address.setText("");
                     Housenumber.setText("");
                     LastName.setText("");
                     FirstName.setText("");
                     MiddleName.setText("");
                     Suffix.setSelectedItem("");
                     Age.setText("");
                     Sex.setSelectedItem("");
                     Birthday.setText("");
                     Status.setSelectedItem("");
                     Relationship.setText("");
                     Religion.setText("");
                     PhoneNumber.setText("");
                     Email.setText("");
                     Educational.setSelectedItem("");

                     Con.close();
                     }catch(Exception e){
                         e.printStackTrace();
                        }
                    }else if(result == JOptionPane.YES_OPTION){
               
                        
                       try{
                       Con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/brgydata","root","");

                      PreparedStatement add =Con.prepareStatement("INSERT INTO familyhead(Head_ID,Family_Heads) Values(?,?)");
                     add.setString(1, MemberID.getText());
                     add.setString(2, LastName.getText()+" "+FirstName.getText());
                       

                        PreparedStatement add2 =Con.prepareStatement("INSERT INTO familyhome(Family_Name,Family_Address,House_number,headID_fk,Home_ID) Values(?,?,?,?,?)");
                     add2.setString(1, LastName.getText());
                     add2.setString(2, Address.getText());
                     add2.setString(3, Housenumber.getText());
                     add2.setString(4, MemberID.getText());
                     add2.setString(5, Housenumber.getText());

                     PreparedStatement add3 =Con.prepareStatement("INSERT INTO familymembers(LastName,FirstName,MiddleName,Suffix,Age,Sex,BirthDate,"
                             + "Status,Relationship,Religion,PhoneNumber,Email,Educational,homeID_fk,Member_ID) Values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                     add3.setString(1, LastName.getText());
                     add3.setString(2, FirstName.getText());
                     add3.setString(3, MiddleName.getText());
                     add3.setString(4, Suffix.getSelectedItem().toString());
                     add3.setString(5, Age.getText());
                     add3.setString(6, Sex.getSelectedItem().toString());
                     add3.setString(7, Birthday.getText());
                     add3.setString(8, Status.getSelectedItem().toString());
                     add3.setString(9, Relationship.getText());
                     add3.setString(10, Religion.getText());
                     add3.setString(11, PhoneNumber.getText());
                     add3.setString(12, Email.getText());
                     add3.setString(13, Educational.getSelectedItem().toString());
                     add3.setString(14, Housenumber.getText());
                     add3.setString(15, MemberID.getText());

                      add.executeUpdate();
                       add2.executeUpdate();
                       add3.executeUpdate();


                       

                       MemberID.setText("");
                       LastName.setText("");
                       Address.setText("");
                       Housenumber.setText("");
                       LastName.setText("");
                       FirstName.setText("");
                       MiddleName.setText("");
                       Suffix.setSelectedItem("");
                       Age.setText("");
                       Sex.setSelectedItem("");
                       Birthday.setText("");
                       Status.setSelectedItem("");
                       Relationship.setText("");
                       Religion.setText("");
                       PhoneNumber.setText("");
                       Email.setText("");
                       Educational.setSelectedItem("");

                       Con.close();
                       }catch(Exception e){
                           e.printStackTrace();
                   }
                       MemberTable1 mt;
                      mt = new MemberTable1();
                      mt.setVisible(true);
          
            }else{
                       JOptionPane.showMessageDialog(this, "Please Choose from the option");
                    }
       // Retrieve the text from the JTextField
        // Convert the text to an integer
       
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
       
            try{
                Con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/brgydata","root","");
               String UpdateQuery = "UPDATE brgydata.familymembers SET LastName='" + LastName.getText() + "', " +                       
                "Member_ID='" + MemberID.getText() + "', " +
                "FirstName='" + FirstName.getText() + "', " +
                "MiddleName='" + MiddleName.getText() + "', " +
                "Suffix='" + Suffix.getSelectedItem() + "', " +
                "Age='" + Age.getText() + "', " +
                "Sex='" + Sex.getSelectedItem() + "', " +
                "BirthDate='" + Birthday.getText() + "', " +
                "Status='" + Status.getSelectedItem() + "', " +
                "Relationship='" + Relationship.getText() + "', " +
                "Religion='" + Religion.getText() + "', " +
                "PhoneNumber='" + PhoneNumber.getText() + "', " +
                "Email='" + Email.getText() + "', " +
                "Educational='" + Educational.getSelectedItem() + "' " +
                "WHERE Member_ID='" + MemberID.getText() + "'";

            String text = LastName.getText() + " " + FirstName.getText();
            String UpdateQuerys = "UPDATE brgydata.familyhead SET Family_Heads='" + text + "' WHERE Family_Heads='" + MemberID.getText() + "'";

                Statement Add = Con.createStatement();
                Add.executeUpdate(UpdateQuery);
                Add.executeUpdate(UpdateQuerys);
                JOptionPane.showMessageDialog(this, "Family Head Updated Successfully");
                FamilyHead();
            }catch(Exception e){
                e.printStackTrace();
            }
        
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        int result = JOptionPane.showConfirmDialog(null, "Do you want to delete the information?", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

if (result == JOptionPane.YES_OPTION) {   
            try{
                Con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/brgydata","root","");
                String Id = MemberID.getText();
                String Id2 = Housenumber.getText();
                String Query = "Delete from brgydata.familyhead where Head_ID="+ Id;
                String Querys = "Delete from brgydata.familyhome where Home_ID="+ Id2;
                Statement Add = Con.createStatement();
                Add.executeUpdate(Query);
                Add.executeUpdate(Querys);
                FamilyHead();
                JOptionPane.showMessageDialog(this, "Family Head Deleted Successfully");
                MemberID.setText("");
                       LastName.setText("");
                       Address.setText("");
                       Housenumber.setText("");
                       LastName.setText("");
                       FirstName.setText("");
                       MiddleName.setText("");
                       Suffix.setSelectedItem("");
                       Age.setText("");
                       Sex.setSelectedItem("");
                       Birthday.setText("");
                       Status.setSelectedItem("");
                       Relationship.setText("");
                       Religion.setText("");
                       PhoneNumber.setText("");
                       Email.setText("");
                       Educational.setSelectedItem("");
            }catch(SQLException e){
                e.printStackTrace();
            }
        }else{
    
}
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
         MemberID.setText("");
                       LastName.setText("");
                       Address.setText("");
                       Housenumber.setText("");
                       LastName.setText("");
                       FirstName.setText("");
                       MiddleName.setText("");
                       Suffix.setSelectedItem("");
                       Age.setText("");
                       Sex.setSelectedItem("");
                       Birthday.setText("");
                       Status.setSelectedItem("");
                       Relationship.setText("");
                       Religion.setText("");
                       PhoneNumber.setText("");
                       Email.setText("");
                       Educational.setSelectedItem("");
    }//GEN-LAST:event_jLabel9MouseClicked

    private void AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressActionPerformed

    private void surnamesearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_surnamesearchMouseClicked
        //surnamesearch.setText("");
    }//GEN-LAST:event_surnamesearchMouseClicked

    private void surnamesearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_surnamesearchKeyPressed

        try{
            String url = "jdbc:mysql://localhost:3307/brgydata";
            Connection conn = DriverManager.getConnection(url,"root","");
            Statement st = conn.createStatement();
            String query = "select familymembers.Member_ID,familyhead.Family_Heads,"
                    + "familyhome.Family_Name,familyhome.Family_Address,familyhome.House_number,familymembers.LastName,"
                    + "familymembers.FirstName,familymembers.MiddleName,familymembers.Suffix,familymembers.Age,"
                    + "familymembers.Sex,familymembers.BirthDate,familymembers.Status,familymembers.Relationship,"
                    + "familymembers.Religion,familymembers.PhoneNumber,familymembers.Email,familymembers.Educational from familyhead inner join familyhome on "
                + "familyhead.Head_ID=familyhome.headID_fk inner join familymembers on familyhome.Home_ID=familymembers.homeID_fk  WHERE familymembers.Relationship = 'Head' AND Family_Heads LIKE '%" + surnamesearch.getText() + "%'";
            Rs = st.executeQuery(query);
            Familyheadinfo.setModel(DbUtils.resultSetToTableModel(Rs));

            conn.close();

        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Got an exception!");
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_surnamesearchKeyPressed

    private void surnamesearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_surnamesearchKeyReleased

        try{
            String url = "jdbc:mysql://localhost:3307/brgydata";
            Connection conn = DriverManager.getConnection(url,"root","");
            Statement st = conn.createStatement();
            String query = "select familymembers.Member_ID,familyhead.Family_Heads,"
                    + "familyhome.Family_Name,familyhome.Family_Address,familyhome.House_number,familymembers.LastName,"
                    + "familymembers.FirstName,familymembers.MiddleName,familymembers.Suffix,familymembers.Age,"
                    + "familymembers.Sex,familymembers.BirthDate,familymembers.Status,familymembers.Relationship,"
                    + "familymembers.Religion,familymembers.PhoneNumber,familymembers.Email,familymembers.Educational from familyhead inner join familyhome on "
                + "familyhead.Head_ID=familyhome.headID_fk inner join familymembers on familyhome.Home_ID=familymembers.homeID_fk  WHERE familymembers.Relationship = 'Head' AND Family_Heads LIKE '%" + surnamesearch.getText() + "%'";
            Rs = st.executeQuery(query);
            Familyheadinfo.setModel(DbUtils.resultSetToTableModel(Rs));

            conn.close();

        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Got an exception!");
            System.err.println(e.getMessage());
        }

    }//GEN-LAST:event_surnamesearchKeyReleased

    private void surnamesearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_surnamesearchKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_surnamesearchKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ad;
    private javax.swing.JTextField Address;
    private javax.swing.JTextField Age;
    private javax.swing.JTextField Birthday;
    private javax.swing.JLabel Educatinal1;
    private javax.swing.JComboBox<String> Educational;
    private javax.swing.JTextField Email;
    private javax.swing.JTable Familyheadinfo;
    private javax.swing.JTextField FirstName;
    private javax.swing.JLabel House;
    private javax.swing.JTextField Housenumber;
    private javax.swing.JTextField LastName;
    private javax.swing.JTextField MemberID;
    private javax.swing.JTextField MiddleName;
    private javax.swing.JTextField PhoneNumber;
    private javax.swing.JTextField Relationship;
    private javax.swing.JTextField Religion;
    private javax.swing.JComboBox<String> Sex;
    private javax.swing.JComboBox<String> Status;
    private javax.swing.JComboBox<String> Suffix;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    public javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private javax.swing.JTextField surnamesearch;
    // End of variables declaration//GEN-END:variables
}
