/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package barangay.information.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ASUS ROG STRIX
 */
public class memberaddinfo extends javax.swing.JPanel {

    /**
     * Creates new form memberaddinfo
     */
    public memberaddinfo() {
        initComponents();
        Familyheads();
        FamilyMembers();
    } Connection Con = null;
Statement St = null;
ResultSet Rs= null;
public void FamilyMembers(){
    
     // Create the table
  
    try{
        Con= DriverManager.getConnection("jdbc:mysql://localhost:3307/brgydata","root","");
        St = Con.createStatement();
        Rs = St.executeQuery("SELECT * FROM familyhead JOIN familyhome ON familyhead.Head_ID = familyhome.headID_fk JOIN familymembers ON familyhome.Home_ID = familymembers.homeID_fk WHERE familyhead.Family_Heads = '"+Familyhead_cb.getSelectedItem()+"'");

        Familymembersinfo.setModel(DbUtils.resultSetToTableModel(Rs));
       
    }catch(SQLException e){
        e.printStackTrace();
        
    }}
public void Familyheads() {
        try {
            Con= DriverManager.getConnection("jdbc:mysql://localhost:3307/brgydata","root","");
            St = Con.createStatement();
            Rs = St.executeQuery("SELECT Family_Heads FROM familyhead");
            
// Add the family head names to the combo box
        while (Rs.next()) {
            String name = Rs.getString("Family_Heads");
            Familyhead_cb.addItem(name);
        }

        // Close the result set, statement, and connection objects
        Rs.close();
        St.close();
        Con.close();
        } catch (Exception ex) {
            Logger.getLogger(memberaddinfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Familymembersinfo = new javax.swing.JTable();
        Familyhead_cb = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        Familymembersinfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Familymembersinfo);

        jLabel1.setText("Family Head");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Familyhead_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(290, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Familyhead_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Familyhead_cb;
    private javax.swing.JTable Familymembersinfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
