/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package barangay.information.system;

import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ASUS ROG STRIX
 */
public class UpdateResident extends javax.swing.JInternalFrame {

    /**
     * Creates new form UpdateResident
     */
    public UpdateResident() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        FamilyMember();
    }
    Connection Con = null;
Statement St = null;
ResultSet Rs= null;
public void FamilyMember(){
    try{
        Con= DriverManager.getConnection("jdbc:mysql://localhost:3307/brgydata","root","");
        St = Con.createStatement();
        Rs = St.executeQuery("select * from familymembers");
        Familymemberinfo.setModel(DbUtils.resultSetToTableModel(Rs));
        
    }catch(SQLException e){
        e.printStackTrace();
        
    }
        
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        panel2 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Familymemberinfo = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        MemberID = new javax.swing.JTextField();
        FirstName = new javax.swing.JTextField();
        MiddleName = new javax.swing.JTextField();
        LastName = new javax.swing.JTextField();
        Suffix = new javax.swing.JComboBox<>();
        Age = new javax.swing.JTextField();
        Sex = new javax.swing.JComboBox<>();
        Birthday = new javax.swing.JTextField();
        Status = new javax.swing.JComboBox<>();
        Religion = new javax.swing.JTextField();
        Relationship = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        PhoneNumber = new javax.swing.JTextField();
        Educational = new javax.swing.JTextField();
        Housenumber = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Educatinal = new javax.swing.JLabel();
        House = new javax.swing.JLabel();
        Ad = new javax.swing.JLabel();
        usernamesearch = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        panel1.setBackground(new java.awt.Color(0, 153, 51));

        panel2.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Familymemberinfo.setAutoCreateRowSorter(true);
        Familymemberinfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Familymemberinfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Familymemberinfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "First Name", "Middle Name", "Last Name", "Suffix", "Age", "Sex", "Birthday", "Civil Status", "Religion", "Relationship", "Email", "Educatinal Attainment", "House Number", "Address"
            }
        ));
        Familymemberinfo.setAutoResizeMode(0);
        Familymemberinfo.setFocusable(false);
        Familymemberinfo.setIntercellSpacing(new java.awt.Dimension(0, 0));
        Familymemberinfo.setOpaque(false);
        Familymemberinfo.setSelectionBackground(new java.awt.Color(0, 153, 51));
        Familymemberinfo.setShowGrid(true);
        Familymemberinfo.getTableHeader().setReorderingAllowed(false);
        Familymemberinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FamilymemberinfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Familymemberinfo);
        if (Familymemberinfo.getColumnModel().getColumnCount() > 0) {
            Familymemberinfo.getColumnModel().getColumn(0).setResizable(false);
            Familymemberinfo.getColumnModel().getColumn(1).setResizable(false);
            Familymemberinfo.getColumnModel().getColumn(2).setResizable(false);
            Familymemberinfo.getColumnModel().getColumn(3).setResizable(false);
            Familymemberinfo.getColumnModel().getColumn(4).setResizable(false);
            Familymemberinfo.getColumnModel().getColumn(5).setResizable(false);
            Familymemberinfo.getColumnModel().getColumn(6).setResizable(false);
            Familymemberinfo.getColumnModel().getColumn(7).setResizable(false);
            Familymemberinfo.getColumnModel().getColumn(8).setResizable(false);
            Familymemberinfo.getColumnModel().getColumn(9).setResizable(false);
            Familymemberinfo.getColumnModel().getColumn(10).setResizable(false);
            Familymemberinfo.getColumnModel().getColumn(11).setResizable(false);
            Familymemberinfo.getColumnModel().getColumn(12).setResizable(false);
            Familymemberinfo.getColumnModel().getColumn(13).setResizable(false);
            Familymemberinfo.getColumnModel().getColumn(14).setResizable(false);
        }

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(0, 1, 0, 6));

        MemberID.setEditable(false);
        jPanel2.add(MemberID);

        FirstName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameActionPerformed(evt);
            }
        });
        jPanel2.add(FirstName);

        MiddleName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(MiddleName);

        LastName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(LastName);

        Suffix.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Jr.", "Sr.", " I", " II", "III", "IV" }));
        Suffix.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(Suffix);

        Age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(Age);

        Sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        Sex.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(Sex);

        Birthday.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(Birthday);

        Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single ", "Married", "Divorced ", "Widowed ", "Separated " }));
        Status.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(Status);

        Religion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(Religion);

        Relationship.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Relationship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelationshipActionPerformed(evt);
            }
        });
        jPanel2.add(Relationship);

        Email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(Email);

        PhoneNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberActionPerformed(evt);
            }
        });
        jPanel2.add(PhoneNumber);

        Educational.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(Educational);

        Housenumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(Housenumber);

        Address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressActionPerformed(evt);
            }
        });
        jPanel2.add(Address);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(0, 1, 0, 6));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("MEMBER ID");
        jPanel1.add(jLabel13);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("First Name");
        jPanel1.add(jLabel1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Middle Name");
        jPanel1.add(jLabel3);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Last Name");
        jPanel1.add(jLabel2);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Suffix");
        jPanel1.add(jLabel7);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Age");
        jPanel1.add(jLabel4);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Sex");
        jPanel1.add(jLabel8);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Birthday");
        jPanel1.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Civil Status");
        jPanel1.add(jLabel6);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Religion");
        jPanel1.add(jLabel9);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Relationship");
        jPanel1.add(jLabel12);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Email");
        jPanel1.add(jLabel11);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Phone Number");
        jPanel1.add(jLabel10);

        Educatinal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Educatinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Educatinal.setText("Educational");
        jPanel1.add(Educatinal);

        House.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        House.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        House.setText("House Number");
        jPanel1.add(House);

        Ad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Ad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ad.setText("Address");
        jPanel1.add(Ad);

        usernamesearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernamesearchMouseClicked(evt);
            }
        });

        jLabel14.setText("Surname");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernamesearch, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(usernamesearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameActionPerformed

    private void RelationshipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelationshipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RelationshipActionPerformed

    private void PhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberActionPerformed

    private void AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressActionPerformed

    private void FamilymemberinfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FamilymemberinfoMouseClicked
       DefaultTableModel model = (DefaultTableModel)Familymemberinfo.getModel();
        int Myindex = Familymemberinfo.getSelectedRow();
        MemberID.setText(model.getValueAt(Myindex, 0).toString());
        LastName.setText(model.getValueAt(Myindex, 1).toString());
        FirstName.setText(model.getValueAt(Myindex,2).toString());
        MiddleName.setText(model.getValueAt(Myindex, 3).toString());
        JComboBox<String> SuffixComboBox = Suffix;
        String Suffix = model.getValueAt(Myindex, 4).toString();
            if (Suffix.isEmpty()) {
                    
                SuffixComboBox.setSelectedIndex(0);
            } else if (Suffix.equals("Jr.")) {
                 SuffixComboBox.setSelectedIndex(1);
            } else if (Suffix.equals("Sr.")) {
                 SuffixComboBox.setSelectedIndex(2);
            } else if (Suffix.equals("I")) {
                 SuffixComboBox.setSelectedIndex(3);
            }else if (Suffix.equals("II")) {
                 SuffixComboBox.setSelectedIndex(4);
            }else if (Suffix.equals("III")) {
                 SuffixComboBox.setSelectedIndex(5);
            }else if (Suffix.equals("IV")) {
                 SuffixComboBox.setSelectedIndex(6);
            }
        Age.setText(model.getValueAt(Myindex, 5).toString());
         JComboBox<String> SexComboBox = Sex;
         String Sex = model.getValueAt(Myindex, 6).toString();
            if (Sex.equals("Male")) {
                    
                SexComboBox.setSelectedIndex(0);
            } else if (Sex.equals("Female")) {
                 SexComboBox.setSelectedIndex(1);
            }
        Birthday.setText(model.getValueAt(Myindex, 7).toString());
           JComboBox<String> StatusComboBox = Status;
        String Status = model.getValueAt(Myindex,8).toString();
            if (Status.equals("Single")) {
                    
                StatusComboBox.setSelectedIndex(0);
            } else if (Status.equals("Married")) {
                 StatusComboBox.setSelectedIndex(1);
            } else if (Status.equals("Divorced")) {
                 StatusComboBox.setSelectedIndex(3);
            } else if (Status.equals("Widowed")) {
                 StatusComboBox.setSelectedIndex(4);
            }else if (Status.equals("Separated")) {
                 StatusComboBox.setSelectedIndex(5);
            }
        Relationship.setText(model.getValueAt(Myindex, 9).toString());
        Religion.setText(model.getValueAt(Myindex, 10).toString());
        PhoneNumber.setText(model.getValueAt(Myindex, 11).toString());
        Email.setText(model.getValueAt(Myindex, 12).toString());
        Educational.setText(model.getValueAt(Myindex, 13).toString());
        
         
    }//GEN-LAST:event_FamilymemberinfoMouseClicked

    private void usernamesearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernamesearchMouseClicked

    }//GEN-LAST:event_usernamesearchMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ad;
    private javax.swing.JTextField Address;
    private javax.swing.JTextField Age;
    private javax.swing.JTextField Birthday;
    private javax.swing.JLabel Educatinal;
    private javax.swing.JTextField Educational;
    private javax.swing.JTextField Email;
    private javax.swing.JTable Familymemberinfo;
    private javax.swing.JTextField FirstName;
    private javax.swing.JLabel House;
    private javax.swing.JTextField Housenumber;
    private javax.swing.JTextField LastName;
    private javax.swing.JTextField MemberID;
    private javax.swing.JTextField MiddleName;
    private javax.swing.JTextField PhoneNumber;
    private javax.swing.JTextField Relationship;
    private javax.swing.JTextField Religion;
    private javax.swing.JComboBox<String> Sex;
    private javax.swing.JComboBox<String> Status;
    private javax.swing.JComboBox<String> Suffix;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private javax.swing.JTextField usernamesearch;
    // End of variables declaration//GEN-END:variables
}
